version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8
    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install Ant
          command: sudo apt-get install ant

      - run:
          name: Install Maven
          command: sudo apt-get install maven

      - run:
          name: Build with Ant
          command: ant

      - run:
          name: Build with Maven
          command: mvn compile

      - run:
          name: Run Tests
          command: mvn test
